### ISSUE TITLE
Pull Request Tasks results in a 404

### ISSUE THREAD

**Issue by AndrewGorman** [githubnext/copilot-workspace-user-manual#31]
The following document is linked in the README but results in a 404: https://github.com/githubnext/copilot-workspace-user-manual/blob/main/pull-request-tasks.md

**Comment by AndrewGorman** [comment]
@dsyme looks like you removed the file in https://github.com/githubnext/copilot-workspace-user-manual/commit/a39c1af320e9208a4b04bc3e40ff86273e526ded but left the reference in the README?

**Comment by dsyme** [comment]
@AndrewGorman Fixed, thanks!
