### ISSUE TITLE
工具データベース作成

### ISSUE THREAD

**Issue by kazu-4728** [githubnext/copilot-workspace-user-manual#32]
マシニングセンターで使用する加工用工具のデータベースを作成する。
Webに公開されている工具メーカーのカタログから工具データと切削条件をリンクさせ、リスト化する。
データベースから工具情報を入力すると切削条件が検索出来るように設定する。

**Comment by kazu-4728** [comment]
> マシニングセンターで使用する加工用工具のデータベースを作成する。 Webに公開されている工具メーカーのカタログから工具データと切削条件をリンクさせ、リスト化する。 データベースから工具情報を入力すると切削条件が検索出来るように設定する。

**Comment by kazu-4728** [comment]
> マシニングセンターで使用する加工用工具のデータベースを作成する。 Webに公開されている工具メーカーのカタログから工具データと切削条件をリンクさせ、リスト化する。 データベースから工具情報を入力すると切削条件が検索出来るように設定する。

**Comment by eaftan** [comment]
Did you intend to open these against the user manual?  Closing as they look unrelated
