### ISSUE TITLE
演算

### ISSUE THREAD

**Issue by kazu-4728** [githubnext/copilot-workspace-user-manual#33]
- C#, .NET 8を使う
- コンソールアプリケーションを作る
- 入力された2つの値で四則演算を行う
- 数字以外の文字の場合は「🙅」と表示する

**Comment by kazu-4728** [comment]
> * C#、.NET 8を使う
> * コンソールアプリケーションを作る
> * 入力された2つの値で四則演算を行う
> * 数字以外の文字の場合は「🙅」と表示する

**Comment by eaftan** [comment]
Did you intend to open these against the user manual?  Closing as they look unrelated
