### ISSUE TITLE
Errors when trying to use Copilot Workspace

### ISSUE THREAD

**Issue by purkhusid** [githubnext/copilot-workspace-user-manual#40]
Hey, just got an invite to Copilot Workspace and went to try it out.

Nothing works and I get the following error:
![image](https://github.com/user-attachments/assets/0a694747-1637-4420-8ae1-b7e758f012d6)

There are also errors in the browser console:
![image](https://github.com/user-attachments/assets/83f0340d-16c7-4cdb-ada5-072e8ec71e4f)

Tested in both Firefox and Chromium

**Comment by dsyme** [comment]
Hi @purkhusid - There seems to have been an outage, I believe it's fixed now. Could you give it another go? Thanks

**Comment by purkhusid** [comment]
It works now. Thanks!
